export const TRANSLATIONS = {
  en: {
    title: "AgriSmart AI",
    tagline: "Your AI Farming Companion",
    detectDisease: "Detect Disease",
    smartFarming: "Smart Farming",
    weather: "Weather",
    chatbot: "AI Chatbot",
    dashboard: "Dashboard",
    uploadImage: "Upload Plant Leaf Image",
    dragDrop: "Drag and drop or click to upload",
    detecting: "Detecting disease...",
    diseaseName: "Disease Name",
    confidence: "Confidence",
    severity: "Severity",
    symptoms: "Symptoms",
    causes: "Causes",
    preventiveMeasures: "Preventive Measures",
    treatment: "Treatment",
    organic: "Organic",
    chemical: "Chemical",
    farmingPlan: "Farming Plan",
    location: "Location",
    month: "Month",
    getPlan: "Get Farming Plan",
    weatherAlerts: "Weather Alerts",
    askMe: "Ask me anything about farming...",
    history: "Scan History",
    noHistory: "No scan history yet.",
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    tamil: "Tamil",
    low: "Low",
    medium: "Medium",
    high: "High",
    rainWarning: "Rain Warning",
    tempChange: "Temperature Change",
    humidityRisk: "Humidity Risk",
    stepByStep: "Step-by-Step Guide",
    soilPrep: "Soil Preparation",
    watering: "Watering Schedule",
    fertilizer: "Fertilizer Recommendations",
    harvest: "Harvest Timeline",
    // New translations for Camera & Auth
    login: "Sign In",
    signup: "Register",
    logout: "Sign Out",
    farmerProfile: "Farmer Profile",
    quickDemoLogin: "Quick Demo Farmer Login",
    demoAccount1: "Farmer Murugan (Paddy & Tomato)",
    demoAccount2: "Farmer Ananya (Horticulture & Spices)",
    orContinueWith: "or enter details manually",
    name: "Full Name",
    emailOrPhone: "Email or Phone Number",
    password: "Password",
    primaryCrops: "Primary Crops Cultivated",
    welcomeBack: "Welcome back",
    guestMode: "Continue as Guest",
    loginRequiredNotice: "Sign in to save records to your personalized farmer account",
    openCamera: "Open Camera",
    capturePhoto: "Capture Photo",
    switchCamera: "Switch Camera",
    retake: "Retake Photo",
    usePhoto: "Use Photo",
    cameraPermissionDenied: "Camera access was denied or is unavailable. Please grant camera permission or use file upload.",
    alignLeafInstruction: "Position the infected leaf clearly in good lighting inside the frame",
    orTrySample: "Or test with a sample infected leaf:",
    sampleTomatoBlight: "Tomato Blight",
    samplePaddyBlast: "Paddy Blast",
    sampleCornRust: "Corn Rust",
    appLinks: "App Share Link",
  },
  ta: {
    title: "அக்ரிஸ்மார்ட் AI",
    tagline: "உங்கள் AI விவசாயத் துணை",
    detectDisease: "நோய் கண்டறிதல்",
    smartFarming: "ஸ்மார்ட் விவசாயம்",
    weather: "வானிலை",
    chatbot: "AI சாட்போட்",
    dashboard: "டாஷ்போர்டு",
    uploadImage: "செடி இலை படத்தைப் பதிவேற்றவும்",
    dragDrop: "பதிவேற்ற இழுத்து விடவும் அல்லது கிளிக் செய்யவும்",
    detecting: "நோயைக் கண்டறிகிறது...",
    diseaseName: "நோயின் பெயர்",
    confidence: "நம்பிக்கை",
    severity: "தீவிரம்",
    symptoms: "அறிகுறிகள்",
    causes: "காரணங்கள்",
    preventiveMeasures: "தடுப்பு நடவடிக்கைகள்",
    treatment: "சிகிச்சை",
    organic: "இயற்கை",
    chemical: "ரசாயனம்",
    farmingPlan: "விவசாயத் திட்டம்",
    location: "இடம்",
    month: "மாதம்",
    getPlan: "விவசாயத் திட்டத்தைப் பெறுங்கள்",
    weatherAlerts: "வானிலை எச்சரிக்கைகள்",
    askMe: "விவசாயம் பற்றி எதையும் என்னிடம் கேளுங்கள்...",
    history: "ஸ்கேன் வரலாறு",
    noHistory: "இன்னும் ஸ்கேன் வரலாறு இல்லை.",
    language: "மொழி",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    english: "ஆங்கிலம்",
    tamil: "தமிழ்",
    low: "குறைவு",
    medium: "நடுத்தரம்",
    high: "அதிகம்",
    rainWarning: "மழை எச்சரிக்கை",
    tempChange: "வெப்பநிலை மாற்றம்",
    humidityRisk: "ஈரப்பதம் அபாயம்",
    stepByStep: "படி-படியாக வழிகாட்டி",
    soilPrep: "மண் தயாரிப்பு",
    watering: "நீர் பாய்ச்சும் அட்டவணை",
    fertilizer: "உரப் பரிந்துரைகள்",
    harvest: "அறுவடை காலவரிசை",
    // New translations for Camera & Auth
    login: "உள்நுழைவு",
    signup: "பதிவு செய்க",
    logout: "வெளியேறு",
    farmerProfile: "விவசாயி சுயவிவரம்",
    quickDemoLogin: "விரைவு விவசாயி மாதிரி உள்நுழைவு",
    demoAccount1: "விவசாயி முருகன் (நெல் & தக்காளி)",
    demoAccount2: "விவசாயி அனன்யா (தோட்டக்கலை & மசாலா)",
    orContinueWith: "அல்லது விவரங்களை உள்ளிடவும்",
    name: "முழுப் பெயர்",
    emailOrPhone: "மின்னஞ்சல் அல்லது கைபேசி எண்",
    password: "கடவுச்சொல்",
    primaryCrops: "பயிரிடப்படும் முதன்மைப் பயிர்கள்",
    welcomeBack: "மீண்டும் வருக",
    guestMode: "விருந்தினராகத் தொடரவும்",
    loginRequiredNotice: "உங்கள் சொந்த கணக்கில் ஸ்கேன் பதிவுகளைச் சேமிக்க உள்நுழையவும்",
    openCamera: "கேமராவைத் திறக்கவும்",
    capturePhoto: "படம் பிடிக்கவும்",
    switchCamera: "கேமராவை மாற்றவும்",
    retake: "மீண்டும் படம் எடு",
    usePhoto: "படத்தைப் பயன்படுத்து",
    cameraPermissionDenied: "கேமரா அனுமதி மறுக்கப்பட்டது அல்லது கிடைக்கவில்லை. கேமரா அனுமதியை வழங்கவும் அல்லது கோப்பைப் பதிவேற்றவும்.",
    alignLeafInstruction: "நோய்த்தொற்று உள்ள இலையைச் சட்டகத்திற்குள் நல்ல வெளிச்சத்தில் வைக்கவும்",
    orTrySample: "அல்லது மாதிரி பாதிக்கப்பட்ட இலையைச் சோதிக்கவும்:",
    sampleTomatoBlight: "தக்காளி கருகல் நோய்",
    samplePaddyBlast: "நெல் குலை நோய்",
    sampleCornRust: "மக்காச்சோள துரு நோய்",
    appLinks: "செயலி பகிர்வு இணைப்பு",
  },
};

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];
