export const TRANSLATIONS = {
  en: {
    title: "AgriSmart AI",
    tagline: "Your AI Farming Companion",
    detectDisease: "Detect Disease",
    smartFarming: "Smart Farming",
    weather: "Weather",
    chatbot: "AI Chatbot",
    dashboard: "Dashboard",
    uploadImage: "Upload Plant Leaf Image",
    dragDrop: "Drag and drop or click to upload",
    detecting: "Detecting disease...",
    diseaseName: "Disease Name",
    confidence: "Confidence",
    severity: "Severity",
    symptoms: "Symptoms",
    causes: "Causes",
    preventiveMeasures: "Preventive Measures",
    treatment: "Treatment",
    organic: "Organic",
    chemical: "Chemical",
    farmingPlan: "Farming Plan",
    location: "Location",
    month: "Month",
    getPlan: "Get Farming Plan",
    weatherAlerts: "Weather Alerts",
    askMe: "Ask me anything about farming...",
    history: "Scan History",
    noHistory: "No scan history yet.",
    language: "Language",
    selectLanguage: "Select Language",
    english: "English",
    tamil: "Tamil",
    low: "Low",
    medium: "Medium",
    high: "High",
    rainWarning: "Rain Warning",
    tempChange: "Temperature Change",
    humidityRisk: "Humidity Risk",
    stepByStep: "Step-by-Step Guide",
    soilPrep: "Soil Preparation",
    watering: "Watering Schedule",
    fertilizer: "Fertilizer Recommendations",
    harvest: "Harvest Timeline",
  },
  ta: {
    title: "அக்ரிஸ்மார்ட் AI",
    tagline: "உங்கள் AI விவசாயத் துணை",
    detectDisease: "நோய் கண்டறிதல்",
    smartFarming: "ஸ்மார்ட் விவசாயம்",
    weather: "வானிலை",
    chatbot: "AI சாட்போட்",
    dashboard: "டாஷ்போர்டு",
    uploadImage: "செடி இலை படத்தைப் பதிவேற்றவும்",
    dragDrop: "பதிவேற்ற இழுத்து விடவும் அல்லது கிளிக் செய்யவும்",
    detecting: "நோயைக் கண்டறிகிறது...",
    diseaseName: "நோயின் பெயர்",
    confidence: "நம்பிக்கை",
    severity: "தீவிரம்",
    symptoms: "அறிகுறிகள்",
    causes: "காரணங்கள்",
    preventiveMeasures: "தடுப்பு நடவடிக்கைகள்",
    treatment: "சிகிச்சை",
    organic: "இயற்கை",
    chemical: "ரசாயனம்",
    farmingPlan: "விவசாயத் திட்டம்",
    location: "இடம்",
    month: "மாதம்",
    getPlan: "விவசாயத் திட்டத்தைப் பெறுங்கள்",
    weatherAlerts: "வானிலை எச்சரிக்கைகள்",
    askMe: "விவசாயம் பற்றி எதையும் என்னிடம் கேளுங்கள்...",
    history: "ஸ்கேன் வரலாறு",
    noHistory: "இன்னும் ஸ்கேன் வரலாறு இல்லை.",
    language: "மொழி",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    english: "ஆங்கிலம்",
    tamil: "தமிழ்",
    low: "குறைவு",
    medium: "நடுத்தரம்",
    high: "அதிகம்",
    rainWarning: "மழை எச்சரிக்கை",
    tempChange: "வெப்பநிலை மாற்றம்",
    humidityRisk: "ஈரப்பதம் அபாயம்",
    stepByStep: "படி-படியாக வழிகாட்டி",
    soilPrep: "மண் தயாரிப்பு",
    watering: "நீர் பாய்ச்சும் அட்டவணை",
    fertilizer: "உரப் பரிந்துரைகள்",
    harvest: "அறுவடை காலவரிசை",
  },
};

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];
